### ISSUE TITLE
feat: add ethereumjs to `hive-devnet-5.yaml`

### ISSUE THREAD

**Issue by danceratopz** [ethpandaops/pectra-devnets#47]
The old hive runner ran `ethereumjs`, but it's missing from the Github action. Could you please add it? 🙏 

Required entries for the `clients.yaml`:

- Devnet 5:
  ```yaml
  - client: ethereumjs
    nametag: master
    build_args:
      baseimage: ethereumjs/ethereumjs-monorepo
      tag: master
  ```  
- Devnet 6:
  ```yaml
  - client: ethereumjs
    nametag: master
    build_args:
      baseimage: ethereumjs/ethereumjs-monorepo
      tag: update-7702-devnet-6
  ```
  
cc @jochem-brouwer
